dist: trusty
language: elixir
elixir:
  - 1.5.0
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.6.0
otp_release:
  - 20.0
sudo: required
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix do deps.compile, test
script:
  - mix coveralls.travis