dist: trusty
language: elixir
elixir:
  - 1.6.0
otp_release:
  - 21.0
sudo: required
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix do deps.compile, test
script:
  - mix coveralls.travis