dist: trusty
language: elixir
elixir:
  - 1.10.2
otp_release:
  - 22.0
services: redis
sudo: required
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix do deps.compile, test
script:
  - mix coveralls.travis