version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.13.1
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: mix test
      - run: mix coveralls.circle
      - run: bash <(curl -s https://codecov.io/bash)